export const presets = {
  topLeft: {
    label: 'warm',
    filterFreq: 700,
    filterQ: 1,
    reverbWet: 0.14,
    distortion: 0,
    oscCount: 1,
    oscDetune: 0,
    reverbDecay: 2.5,
    gain: -10,
  },
  topRight: {
    label: 'glasachtig',
    filterFreq: 4500,
    filterQ: 2,
    reverbWet: 0.55,
    distortion: 0,
    oscCount: 3,
    oscDetune: 18,
    reverbDecay: 4.5,
    gain: -8,
  },
  bottomLeft: {
    label: 'donker',
    filterFreq: 220,
    filterQ: 6,
    reverbWet: 0,
    distortion: 0,
    oscCount: 4,
    oscDetune: 8,
    reverbDecay: 1.5,
    gain: -10,
  },
  bottomRight: {
    label: 'agressief',
    filterFreq: 2200,
    filterQ: 10,
    reverbWet: 0,
    distortion: 0.7,
    oscCount: 4,
    oscDetune: 45,
    reverbDecay: 0.6,
    gain: -7,
  },
}
